hobbies:
  - id: "hobby_1"
    icon: "ğŸ’°"
    name: "Trading"
    skill_bonus:
      skill_1: 1.2
      skill_2: 1.1
    effects:
      effect_1:
        id: "effect_1"
        amount_per_turn: 1.1
      effect_2:
        id: "effect_2"
        amount_per_turn: 0.5

  - id: "hobby_2"
    icon: "âš’ï¸"
    name: "Crafting"
    skill_bonus:
      skill_3: 1.3
      skill_4: 1.2
    effects:
      effect_3:
        id: "effect_3"
        amount_per_turn: 1.2
      effect_4:
        id: "effect_4"
        amount_per_turn: 0.8

needs:
  - "need_1"
  - "need_2"
  - "need_3"

perks:
  - "perk_1"
  - "perk_2"
  - "perk_3"

buffs:
  - "buff_1"
  - "buff_2"
  - "buff_3"